# Generated by Django 5.2.5 on 2025-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='콘텐츠'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateField(auto_now_add=True, verbose_name='수정일'),
        ),
    ]
