# Generated by Django 5.2.5 on 2025-08-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_article_content_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '메모',
                'verbose_name_plural': '메모 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
